### ISSUE TITLE
Question: What is the behavior of customTraceNumbers in ValidateOpts?

### ISSUE THREAD

**Issue by tipputhynhean** [wadearnold/ach#1005]
In the docs https://moov-io.github.io/ach/create-file/ , there's the validation options section. I'm not sure what the `customTraceNumbers` does. Any help is appreciated. Thanks!

**Comment by adamdecaf** [comment]
The Nacha/ACH spec requires that trace numbers follow a few rules. That validation option disables them.

- [ascending order of trace numbers within batches](https://github.com/moov-io/ach/blob/v1.14.0/batch.go#L362-L366)
- [trace numbers beginning with their ODFI's routing number](https://github.com/moov-io/ach/blob/v1.14.0/batch.go#L376-L383)
- [`AddendaRecordIndicator` is set correctly](https://github.com/moov-io/ach/blob/v1.14.0/batch.go#L822)

I'll update the docs to better reflect this.
