### ISSUE TITLE
Return batch with offset throws validation error

### ISSUE THREAD

**Issue by jcgarciaram** [wadearnold/ach#1010]
ACH Version: `v1.15.0`

**What were you trying to do?**
Add an offset to a return batch. This was done by calling
```go
batch.WithOffset(&ach.Offset{
	RoutingNumber: "DUMMY",
	AccountNumber: "DUMMY",
	AccountType: "checking",
	Description: "S",
})
batch.Create()
```

**What did you expect to see?**
Successful creation

**What did you see?**
Error: 
```go
batch #1 (WEB) Addenda99 is a mandatory field and has a default value
```

While debugging and stepping through the code, we see that the error is being thrown by the OFFSET entry that gets added during the build step.

The offset entry is created internally as a last step in the `build` method that is called by `batch.Create()` and is given the same category as the first entry in the batch, which in this case is `CategoryReturn`. However, since it's an OFFSET record, it doesn't get an `Addenda99` record. 

When `Validate()` gets called on the batch, it loops through all the entries (including the OFFSET record) and errors out on the `addendaFieldInclusionReturn` when validating the OFFSET record.

**How can we reproduce the problem?**
Very simple example with dummy data. 

```go
package main

import (
	"fmt"
	"time"

	"github.com/moov-io/ach"
)

func main() {
	// Batch Header
	batchHeader := ach.NewBatchHeader()
	batchHeader.ServiceClassCode = 200
	batchHeader.CompanyName = "COMPANY"
	batchHeader.CompanyIdentification = "IDENTIFICATION"
	batchHeader.StandardEntryClassCode = ach.WEB
	batchHeader.CompanyEntryDescription = "DESCRIPTION"
	batchHeader.CompanyDescriptiveDate = time.Now().Format("060102")
	batchHeader.EffectiveEntryDate = time.Now().Add(time.Hour * 24).Format("060102")
	batchHeader.ODFIIdentification = "1"

	// Addenda99
	addenda99 := ach.NewAddenda99()
	addenda99.ReturnCode = "R07"
	addenda99.OriginalTrace = "99912340000015"
	addenda99.AddendaInformation = "Authorization Revoked"
	addenda99.OriginalDFI = "9101298"

	// Entry
	entry := ach.NewEntryDetail()
	entry.TransactionCode = 22
	entry.RDFIIdentification = "1"
	entry.CheckDigit = "3"
	entry.DFIAccountNumber = "DUMMY"
	entry.Amount = 1000
	entry.IndividualName = "DOE, JOHN"
	entry.Category = ach.CategoryReturn
	entry.Addenda99 = addenda99
	entry.AddendaRecordIndicator = 1

	// Batches
	batch1 := ach.NewBatchWEB(batchHeader)
	batch1.AddEntry(entry)

	// Prints nil
	fmt.Printf("batch1 error: %v\n", batch1.Create())

	batch2 := ach.NewBatchWEB(batchHeader)
	batch2.AddEntry(entry)
	batch2.WithOffset(&ach.Offset{
		RoutingNumber: "100000007",
		AccountNumber: "DUMMY",
		AccountType:   "checking",
		Description:   "S",
	})

	// Prints error
	fmt.Printf("batch2 error: %v\n", batch2.Create())
}
```

Go playground link: https://go.dev/play/p/EwWCywnMq_1

**Comment by adamdecaf** [comment]
Thanks for the report! I never thought about adding OFFSET records to returns... Do you expect the same 99 addenda on the OFFSET EntryDetail? I would think it should be a Forward, but your use-case is new to me.

**Comment by adamdecaf** [comment]
I've made a change to [copy over those addenda records](https://github.com/moov-io/ach/pull/1011) which should work for you, but I want to chat with some ACH folks to get their thoughts on this. 

I assume you can manually add the Addenda99 record to work around this?

**Comment by jcgarciaram** [comment]
Hello! Thank you very much for looking into this.

Well, actually we cannot add an Addenda99 record to the OFFSET record. All of the below that I described in the issue happens inside of the `batch.Create()` method _after_ calling the `WithOffset` method on the batch (see example):

> The offset entry is created internally as a last step in the build method that is called by batch.Create() and is given the same category as the first entry in the batch, which in this case is CategoryReturn. However, since it's an OFFSET record, it doesn't get an Addenda99 record.
> 
> When Validate() gets called on the batch, it loops through all the entries (including the OFFSET record) and errors out on the addendaFieldInclusionReturn when validating the OFFSET record.

Also, since there is a single OFFSET record per batch, and a single batch can contain multiple transactions, each with its own Addenda99 record, it doesn't make much sense to add an Addenda99 record.

Thinking through how to solve this, I would probably suggest adding a `validationOption` option to `BypassAddendaFieldInclusion` and setting that to `true` when generating the Offset entry.

**Comment by adamdecaf** [comment]
> Thinking through how to solve this, I would probably suggest adding a validationOption option to BypassAddendaFieldInclusion and setting that to true when generating the Offset entry.

Yea. I'll take a look at doing something like that. We can probably fix the math internally as well.

**Comment by adamdecaf** [comment]
@jcgarciaram I've updated https://github.com/moov-io/ach/pull/1011 to skip that `addendaFieldInclusion` check for OFFSET records. That should resolve the issue you're seeing.

**Comment by adamdecaf** [comment]
Can you try `go get github.com/moov-io/ach@master` and verify your issue is resolved? I'll release a bugfix if it works for you.

**Comment by adamdecaf** [comment]
@jcgarciaram have you had a chance to verify if this fix works?

**Comment by adamdecaf** [comment]
I'm releasing v1.16.0 with this change included. Please let us know if you continue to run into issues. Thanks!

**Comment by jcgarciaram** [comment]
Apologies for the delay in answering. YES! This change accomplishes what we needed. Thank you very much!
