### ISSUE TITLE
Settlement date in batch header not marshaled

### ISSUE THREAD

**Issue by ckbaum** [wadearnold/ach#1029]
ACH Version: `1.17.0`

Because [settlementDate](https://github.com/moov-io/ach/blob/master/batchHeader.go#L100) is an unexported field on `BatchHeader`, it doesn't get included in JSON when the struct is marshaled. This is a pretty critical piece of information for my group's use case; would it be okay to export this field? Seems like it's the only piece of data from the ACH file that isn't represented in the marshaled JSON (besides record type, which can be inferred.)

**Comment by adamdecaf** [comment]
Yep, we can export that field to include in the JSON.

**Comment by adamdecaf** [comment]
I've made a new release with this, thanks! 

https://github.com/moov-io/ach/releases/tag/v1.18.0
