### ISSUE TITLE
reader: static prefix breaks parsing 

### ISSUE THREAD

**Issue by adamdecaf** [wadearnold/ach#1037]
ACH Version: `v1.18.1`

**What did you see?**
Vendors sometimes prefix lines with custom data that needs to be removed. Files and records are in Nacha format except for this prefix. 

**What did you expect to see?**
A handy way to strip these prefixes would help projects like ACHGateway to process these.

**Comment by adamdecaf** [comment]
@zbruhnke do you have an example for ACH?

**Comment by adamdecaf** [comment]
I think this is best solved with a `ValidateOpts` field for a prefix to strip off each line. Functions cannot be serialized across json/yaml so we can't implement a generic routine. 

Should we have an array of prefixes to trim?

**Comment by wadearnold** [comment]
I assume this is only for the file reader and not JSON? Is this something that should be configurable or is there static vars that we can iterate over to avoid? 
I am sure we could put some logic in the Reader 
https://github.com/moov-io/ach/blob/master/reader.go#L114
or here
https://github.com/moov-io/ach/blob/364497ec3bfe3928ac298ef436050ba9eb87dc48/reader.go#L160

**Comment by adamdecaf** [comment]
This is only for the Nacha format. It was a vendor applying a prefix, but the original reporter of this issue trimmed the files prior to parsing. 

I don't know if this belongs in the library or not. It seems like a stretch to include `strings.TrimPrefix(...)` functionality when it can be easily called outside of moov-io/ach.

**Comment by wadearnold** [comment]
Should we close the ticket then?
