### ISSUE TITLE
R62 Missing from valid return codes

### ISSUE THREAD

**Issue by kmyers94** [wadearnold/ach#1043]
ACH Version: `1.13.0`

**What were you trying to do?**
R62 is a valid ACH return code however adding such a return causes a field validation error here: addenda99.go:151. This seems to be because the `returnCodeDict` does not define the appropriate return code. The definition is here: addenda99.go:237
**What did you expect to see?**
No validation error for R62

**What did you see?**
`batch #1 (WEB) FieldError ReturnCode R62 found is not a valid return code`

**How can we reproduce the problem?**
Create a return with an R62 return code

**Comment by adamdecaf** [comment]
Yep. I'm not sure how those got missed, but we can add them.

**Comment by adamdecaf** [comment]
Thanks for the bug report. `v1.18.3` is being released and will be available soon as a Docker image. You can use it as a Go library right now.
