### ISSUE TITLE
Entry categories are not correctly assigned by Reader

### ISSUE THREAD

**Issue by ckbaum** [wadearnold/ach#1045]
ACH Version: `1.18.3`

When ACH files are parsed by `Reader`, the `Category` field of resulting `EntryDetails` is not always set correctly.

| Expectation  | Result | Notes
| ------------- | ------------- | ------------- |
| "Forward" | "" | `NewEntryDetail()` sets "Forward" as the default `Category`, but `Reader` uses `new(EntryDetail)` instead |
| "Return" | "Return" | ✅ |
| "DishonoredReturn" | "Return" | Maybe intended, but the existence of a `CategoryDishonoredReturn` constant suggests it would be used in this scenario |
| "DishonoredReturnContested" | "Return" | ^ same as above, I'd expect the `CategoryDishonoredReturnContested` constant to be used here |
| "NOC" | "NOC" | ✅ |

**Comment by adamdecaf** [comment]
Thanks for the report. That's a bug and I'll release a bugfix this morning.

**Comment by adamdecaf** [comment]
I'm releasing v1.18.4 with this fix.
