### ISSUE TITLE
GET File Contents not working when file is created with JSON

### ISSUE THREAD

**Issue by zbruhnke** [wadearnold/ach#1047]
ACH Version: `v1.14.0`

**What were you trying to do?**
GET File Contents after creating a file via JSON with the `/files/create` endpoint

**What did you expect to see?**
Expected to see a NACHA formatted file

**What did you see?**
Logs showed not found but request is a 200 OK with no response body

**How can we reproduce the problem?**
Create a new file with JSON using the `/files/create` endpoint then take the ID returned from that and run a GET on `/files/{fileId}/contents`

**Comment by zbruhnke** [comment]
FWIW I just tried this on the new release locally `v1.18.3` and I cannot replicate

**Comment by adamdecaf** [comment]
If this is working on v1.18.3 then I don't see anything to fix.
