### ISSUE TITLE
R36 Missing from valid return codes

### ISSUE THREAD

**Issue by jcgarciaram** [wadearnold/ach#1048]
ACH Version: `v1.18.3`

**What were you trying to do?**
Generate a file with a transaction being returned with an **R36: Return of Improper Credit Entry** return code.

**What did you expect to see?**
Successful file generation.

**What did you see?**
`batch #1 (WEB) FieldError ReturnCode R36 found is not a valid return code`

**How can we reproduce the problem?**
Create a return with an R36 return code

**Comment by jcgarciaram** [comment]
Thank you very much @adamdecaf !!

**Comment by adamdecaf** [comment]
I've released v1.18.5 with this fix https://github.com/moov-io/ach/releases/tag/v1.18.5 Thanks again!
