### ISSUE TITLE
Allow a user to generate an ID for a created NACHA file

### ISSUE THREAD

**Issue by zbruhnke** [wadearnold/ach#1059]
ACH Version: `v1.18.5`

**What were you trying to do?**
Started from this [slack convo](https://moov-io.slack.com/archives/CD9J8EJKX/p1658701673979909)

> have you considered allowing folks to create a fileId when submitting a file to ACH via API with NACHA formatting?

**What did you expect to see?**
In `ACH` it would be nice to have an endpoint similar to the one in ACH Gateway where you can choose the `fileId` for a newly created file 

> I’m only asking because we use UUID v4 basically everywhere else including when we’re submitting outgoing ones to ACH Gateway, however if we get an inbound file right now and submit it to ACH then we end up with a ID that looks like this `a19f3f5e13e3a2082e62bd544bdc211844a44591` for me this just feels wrong and I’d love an option to choose the File ID instead if that’s at all possible

**What did you see?**
a POST to `/files/create` generates a UUID in a different format than the UUID v4 that we typically use

Ideally we'd be able to do this by a POST to `files/create/{UUID}` 

**How can we reproduce the problem?**
just create an ACH file via `JSON` or `NACHA` formatting

**Comment by adamdecaf** [comment]
This already works with JSON. Specify the `id` at the root level. I'll double check this for Nacha, but I think we can adopt this easily.

**Comment by zbruhnke** [comment]
yep agree it works with JSON, this is only in the case of being the RDFI and processing a file that is in NACHA format! 

Appreciate the MR!
