### ISSUE TITLE
Dishonored return trace number not parsed correctly

### ISSUE THREAD

**Issue by bulhi** [wadearnold/ach#1064]
ACH Version: `latest`

**What were you trying to do?**
Parse a contested dishonored return, e.g.:

```
101 123456780 0610001462208061450A094101                       SimBank                        
5200SimFintech                          123123123 WEBHammerTime      220307   1364275030000001
621123456780122455799        0000001560               Bruce Wayne           S 1364275034310088
799R72123456780000069      75639218   7563921800000010670112345678000007021868 364275034310088
82000000020012345678000000000000000000001560123123123                          364275030000001
9000001000001000000020012345678000000000000000000001560                                       
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
```

**What did you expect to see?**
`DishonoredReturnTraceNumber = "123456780000070"`

**What did you see?**
`DishonoredReturnTraceNumber = "23456780000070"`

**How can we reproduce the problem?**
Parse the file above in the command line or in-browser tool.

I believe the problem is in `Addenda99Contested.Parse()` where
`Addenda99Contested.DishonoredReturnTraceNumber = record[59:73]`
should really be
`Addenda99Contested.DishonoredReturnTraceNumber = record[58:73]`

The following field (`DishonoredReturnSettlementDate`) seems to be parsed incorrectly too.

**Comment by adamdecaf** [comment]
Thanks for the bug report. You're correct those indexes are off.

**Comment by adamdecaf** [comment]
A fix has been released. Can you try https://github.com/moov-io/ach/releases/tag/v1.18.6 ?

**Comment by bulhi** [comment]
Looking good, thank you!
