### ISSUE TITLE
`ID` vs `id` mismatch in openapi spec vs the ach service

### ISSUE THREAD

**Issue by davidpricedev** [wadearnold/ach#1086]
ACH Version: `1.18.1` (although I see the same issue is present in 1.20 too)

**What were you trying to do?**

Trying to use the typescript typing in https://github.com/moov-io/ach-node-sdk (which are derived directly from the openapi spec yaml file)

**What did you expect to see?**

I expected the typescript field names to precisely match up to the field names that I got back from the ach service. so I could use the typescript to inform intellisense and provide compile-time type correctness.

**What did you see?**

When running a `GET` of `/files/{fileId}`:
The service is returning fields named `id` in a bunch of places in the json that is returned, however the spec (and the derived typescript typing) indicates those fields should be named `ID` - and as a result the supplied typescript types are wrong. 

**How can we reproduce the problem?**

1. POST any ach file to the ach service
2. GET the json format for that file from `/files/{fileId}`
3. Open up https://github.com/moov-io/ach/blob/master/openapi.yaml in a browser
4. Compare the GET results to the spec, noting that the service returns fields named `id` where the spec says they should be named `ID`

For instance the top-level file container object: 

- typescript typings: https://github.com/moov-io/ach-node-sdk/blob/master/api.ts#L1769
- I think that corresponds to this in the openapi spec: https://github.com/moov-io/ach-node-sdk/blob/master/api.ts#L1769
- I think that corresponds to this code: https://github.com/moov-io/ach/blob/master/file.go#L58

This same `id` vs `ID` issue seems to occur for many of the nested objects too, not just that top-level file container

**Comment by adamdecaf** [comment]
Thanks for opening this @davidpricedev! Go is more lenient in allowing `ID` vs `id` to act as the same key. I've opened https://github.com/moov-io/ach/pull/1087 to enforce lowercase across the models. Once that's merged we can release ach-node-sdk with the fix.

**Comment by adamdecaf** [comment]
We've released a bugfix for ach https://github.com/moov-io/ach/releases/tag/v1.20.1

Also I released v1.6.0 of ach-node-sdk. Can you try it out and let us know if that works? 

https://www.npmjs.com/package/ach-node-sdk/v/1.6.0
