### ISSUE TITLE
achcli Custom Validation

### ISSUE THREAD

**Issue by wei** [wadearnold/ach#1096]
### ACH Version

1.21.2

### What were you trying to do?

I am looking to add [Validation options](https://moov-io.github.io/ach/custom-validation/) when using achcli.

### What did you expect to see?

I am expecting a command argument or similar to allow for [custom validations](https://moov-io.github.io/ach/custom-validation/).

**Comment by adamdecaf** [comment]
That seems like a good improvement. I think command line flags are case-sensitive so `-validateOpts. allowUnorderedBatchNumbers` would work but could only be specified in that exact case. I'm fine with that, but we could read a JSON config file as well. 

```json
{
  "validateOpts": {
    "allowUnorderedBatchNumbers": true
  }
}
```
