### ISSUE TITLE
ach-cli Parse IAT Batch/Entries/Addendas

### ISSUE THREAD

**Issue by susansubedi1** [wadearnold/ach#1097]
### ACH Version

1.21.2

### What were you trying to do?

I am trying to view IAT Batch and Entries associated with them using ach-web-viewer. Since, it calls ach-cli to read the ach file, I want to add the ability to parse out IAT Batches, IATEntries and Addenda Records associated with them

### What did you expect to see?

I am expecting to view IAT records using both cli and web-viewer

**Comment by adamdecaf** [comment]
Yep, that should be supported. Let us know if some of the Addenda records for IAT aren't quite right.
