### ISSUE TITLE
Feature Request: ValidateOpt to allow invalid Check Digits

### ISSUE THREAD

**Issue by AndrewPecha** [wadearnold/ach#1107]
### ACH Version

1.21.2

### What were you trying to do?

I was attempting to parse an entire ACH file to JSON using the /create POST endpoint, then retrieving the JSON representation using the /files/{id} endpoint.

The ACH file is known to have an incorrect check digit in the RDFI of a couple Entry Detail lines

### What did you expect to see?

I expected to be able to retrieve the JSON representation in it's entirety, regardless if a check digit is not correct given the RDFI in an Entry Detail record. Instead, the Entry Detail lines with invalid check digits are omitted from the resulting JSON

It would be awesome to have a ValidateOpt option to allow the check digit validation to be bypassed, maybe something like "allowInvalidCheckDigits"?

**Comment by adamdecaf** [comment]
Sounds like a good ValidateOpt to add. Do you plan to open a PR?

**Comment by AndrewPecha** [comment]
> Sounds like a good ValidateOpt to add. Do you plan to open a PR?

Thanks for the quick response! I can definitely work on it, just wanted to ensure this was something of value from your perspective before I began.

Will have some time over the next few days and we can look to go forward from there!

**Comment by adamdecaf** [comment]
@AndrewPecha I'm planning to make this change tomorrow (10/25). We've got some changes for a v1.22 release and this is the last item. If you'd like to open a PR I'd happily help get it merged, but no worries if you're unable to.

**Comment by AndrewPecha** [comment]
Thanks for your patience! I have [submitted a PR](https://github.com/moov-io/ach/pull/1114)

Please let me know your thoughts, and thanks for the opportunity to contribute

**Comment by adamdecaf** [comment]
Fixed by https://github.com/moov-io/ach/pull/1114
