### ISSUE TITLE
docs: include page/section on Effective Entry Date calculation

### ISSUE THREAD

**Issue by adamdecaf** [wadearnold/ach#1118]
We should write up a page detailing how to use moov-io/base and cutoff window calculations to set the EffectiveEntryDate on batches.

**Comment by ChillOrb** [comment]
Hey @adamdecaf is this still relevant ? if yes , please point me to the docs where i can learn more about calculations for EffectiveEntryDate  ? 
1. What specific functionalities should the documentation cover?

2. Also, will this document be a part of /ach repo? 

Appreciate your time!

**Comment by adamdecaf** [comment]
@ChillOrb Yes this document can still be written. I think it should go in the "ACH File Setup" [section of our docs](https://moov-io.github.io/ach/create-file/).

![Screenshot 2023-08-14 at 9 16 55 AM](https://github.com/moov-io/ach/assets/120951/62992077-4523-466d-9431-26feefd9be59)

I'd call it "Calculating Effective Date" and the page should include topics like the following:

- On debits determine good funds hold (e.g. 2 banking days)
- If over SameDay limit push EED to [next banking day](https://pkg.go.dev/github.com/moov-io/base#Time.AddBankingDay)
- Determine if we have enough time today for same-day, otherwise bump to next day (e.g. for credits)
- Skip ahead if on weekends and bank holidays

**Comment by Klasens** [comment]
Hi @adamdecaf, would this still be a good contribution? Is there an alternative good first issue you would suggest?

**Comment by adamdecaf** [comment]
Yea this would be a great issue. I can help proof read.

**Comment by Klasens** [comment]
Okay great. I'm looking at the ach and base Repos more closely and would like to make sure I'm thinking about this document similar to how you are.

If I understand correctly, we want to detail how to use the functions from /base time package -- IsBankingDay, IsBusinessDay, IsHoliday, IsWeekend to calculate the effective entry date of a specific ACH Batch?

Is the objective of this document to educate the user on _how_ to calculate the effective entry date generally, or are you thinking it should provide explicit code snippets that use moov-io/base functions in combination with the moov-io/ach library? or both?

**Comment by adamdecaf** [comment]
Yes you'd use those functions together to help calculate the effective entry date. Same Day's entry limit of $1M applies as well, as does creating entries after all Fed windows are available. 

I would think that explicit code mixed in with descriptions and paragraphs explaining the steps would be ideal.

**Comment by Klasens** [comment]
Okay @adamdecaf, here's two sections. As I was looking at the moov-io/base functions, I felt like I needed to add context around the Effective Entry Date rules and constraints so I added a section that outlined the different constraints for EEDs. This made implmenting the time functions more straightforward.

I pulled information mainly from OR118 - OR119 in the Nacha Operating Rules and Guidelines but also referenced OR69 - OR70, OR131, OG86, OG115.

Cutoff Windows - https://www.frbservices.org/resources/resource-centers/same-day-ach/fedach-processing-schedule.html

I was trying not to get too verbose and wanted to send you something before I spent too much time going down a possibly incorrect path. Let me know if this is the direction you were thinking and if you want to see other topics covered or different implementations.

**Comment by Klasens** [comment]
# Effective Entry Date Field Constraints

## 1. Transmission Windows for Same-Day ACH

There are three transmission deadlines:

* **1st Cutoff**: 10:30 a.m. ET
* **2nd Cutoff**: 2:45 p.m. ET
* **3rd Cutoff**: 4:45 p.m. ET

Files must be submitted before the last cutoff time to be eligible for same-day processing.

If a file is submitted after the last cutoff, entries that list the current banking day as their Effective Entry Date will be settled on the next banking day.

## 2. Same-Day ACH Transaction Limit

* The per-entry limit for same-day ACH is **$1,000,000**
* Entries exceeding this amount are not eligible for same-day settlement
* In a batch containing entries over the limit, those entries will have their Effective Entry Date adjusted to the next banking day and remaining items will still be eligible for same-day settlement

## 3. Credit Entries

For credit entries, the Effective Entry Date must be either:
* The **same banking day** as the processing date for **Same Day Entries**, or
* **One or two banking days** following the processing date for other entries

## 4. Debit Entries

For debit entries, the Effective Entry Date must be either:
* The **same banking day** as the processing date for **Same Day Entries**, or
* **One banking day** following the processing date for other entries

**Note:** Receiving banks may place holds on ACH debits per their funds availability policies, separate from these settlement times.

## 5. Effective Entry Date - Edge Cases

### ENR Entries
* For Automated Enrollment Entries (ENR), the Effective Entry Date field must be **space-filled**
* ENR entries cannot be Same Day Entries

### Notifications of Change
* The ACH Operator does **not edit** the Effective Entry Date field for Notifications of Change

### Return Entries
* The ACH Operator may verify that the Effective Entry Date is properly formatted and may replace the field's existing content with the current processing date if the Effective Entry Date is invalid

**Comment by Klasens** [comment]
# Calculating Effective Entry Dates Using moov-io/base Functions

## Overview

The moov-io/base package provides functionality for calculating valid Effective Entry Dates when creating ACH batch headers, ensuring compliance with NACHA rules and Federal Reserve processing schedules.

## Creating Batch Headers

The NewBatchHeader function creates a BatchHeader object that requires several key fields to be populated according to NACHA rules:

```go
bh := NewBatchHeader()
bh.ServiceClassCode = "220"                  // 220 for credits only
bh.StandardEntryClassCode = PPD              // PPD, CCD, WEB, etc.
bh.CompanyName = "ACME Corporation"          // Your company name
bh.CompanyIdentification = "121042882"       // Your company ID
bh.CompanyEntryDescription = "PAYROLL"       // Transaction description
bh.ODFIIdentification = "12104288"           // Your bank's routing number

bh.EffectiveEntryDate = "240102"             // YYMMDD format
```

## Banking Day Functions

The moov-io/base Time package provides these essential functions for determining valid banking days:

* `AddBankingTime(hours, minutes, seconds int)`: Increments time by specified duration while respecting banking hours (9am-5pm ET)
* `AddBankingDay(d int)`: Adds the specified number of valid banking days to a date
* `IsBankingDay()`: Validates if a date is a banking day by checking both holidays and weekends
* `IsBusinessDay()`: Determines if a date is a standard business day
* `IsHoliday()`: Checks if a date falls on a Federal Reserve holiday
* `IsWeekend()`: Verifies if a date falls on Saturday or Sunday

## Transmission Windows

The package handles Same-Day ACH transmission windows with time-based validations. Here's how to implement the cutoff time checks:

```go
now := base.Now()
// Create cutoff times for each window
firstCutoff := now.AddBankingTime(10, 30, 0)    // 10:30 AM ET
secondCutoff := now.AddBankingTime(14, 45, 0)   // 2:45 PM ET
thirdCutoff := now.AddBankingTime(16, 45, 0)    // 4:45 PM ET

if now.Before(firstCutoff.Time) {
   // In first window
   bh.EffectiveEntryDate = now.Format("060102")
} else if now.Before(secondCutoff.Time) {
   // First window closed, in second window
   bh.EffectiveEntryDate = now.Format("060102")
} else if now.Before(thirdCutoff.Time) {
   // Second window closed, in third window
   bh.EffectiveEntryDate = now.Format("060102")
} else {
   // All windows closed for today
   now = now.AddBankingDay(1)
   bh.EffectiveEntryDate = now.Format("060102")
}
```

## Implementation Example

Here's a complete example showing how to calculate an Effective Entry Date based on various conditions:

```go
func calculateEffectiveEntryDate(amount int, isCredit bool) string {
   now := base.Now()
   
   // On weekends and holidays, entries must be processed on future banking days
   if !now.IsBankingDay() {
       if amount <= 1000000 {
           // Same day entries settle on the next available banking day
           // Example: Saturday file -> Monday settlement
           now = now.AddBankingDay(1)
           return now.Format("060102")
       } else {
           // Non same-day entries must settle beyond the next banking day
           // to prevent inadvertent same-day settlement
           // Example: Saturday file -> Tuesday settlement (skipping Monday)
           now = now.AddBankingDay(1) // Move to next banking day (Monday)
           now = now.AddBankingDay(1) // Move one more day (Tuesday) to maintain non same-day settlement
           return now.Format("060102")
       }
   }
   
   // The last cutoff for same-day ACH is 4:45 PM ET
   thirdCutoff := now.AddBankingTime(16, 45, 0)
   if now.After(thirdCutoff.Time) {
       // After the cutoff, entries follow the same rules as non-banking days
       if amount <= 1000000 {
           // Same day entries settle next banking day
           now = now.AddBankingDay(1)
       } else {
           // Non same-day entries must settle two banking days out
           now = now.AddBankingDay(2)
       }
       return now.Format("060102")
   }
   
   // Before the cutoff on a banking day, same-day settlement is available
   if amount <= 1000000 {
       // Entries within same-day limits can settle today
       return now.Format("060102")
   }
   
   // Non same-day entries must settle at least one banking day after creation
   now = now.AddBankingDay(1)
   return now.Format("060102")
}

**Comment by adamdecaf** [comment]
That's a great overview of the steps involved with picking an EED. Can you open a PR so I can help fixup a couple things? Thanks for your help writing this page!
