### ISSUE TITLE
ACH server API documentation broken links 

### ISSUE THREAD

**Issue by wadearnold** [wadearnold/ach#1125]
### ACH Version

all 

### What were you trying to do?

Reading the documentation there is a link for the REST API that goes to a 404 when trying to follow how to post a JSON file.  
https://moov-io.github.io/ach/create-file/#upload-a-json-representation 
<img width="720" alt="Screenshot 2022-11-03 at 3 42 06 PM" src="https://user-images.githubusercontent.com/32989/199847910-5d751561-7086-4b21-8408-00155c9aa85f.png">

This takes you to a link that is no longer valid. 
https://api.moov.io/#operation/createFile

The same file errors below on the same page for creating a file 
https://api.moov.io/#operation/createFile

### What did you expect to see?

It would be nice to have a link to the server API specification from the readme and have this broken link fixed. 
I think that we want people to go here. But need to confirm with @adamdecaf if this is the most up-to-date API specification 

https://moov-io.github.io/ach/api/#get-/files/-fileID- 

### What did you see?

none

### How can we reproduce the problem?

visit the webpage

**Comment by adamdecaf** [comment]
Thanks for reporting this @wadearnold! The docs will refresh in a minute or two.
