### ISSUE TITLE
Addenda Transaction Type is case sensitive but that is not a NACHA requirement

### ISSUE THREAD

**Issue by kmyers94** [wadearnold/ach#1126]
### ACH Version

1.18.5

### What were you trying to do?

Receiving an Addenda 10 record the transaction type can be lowercase. However, validation disallows lowercase entries.

https://github.com/moov-io/ach/blob/4b6da1cc19af79a153e1b9a98ce6b0159ea52c86/validators.go#L396L403

### What did you expect to see?

Lowercase Transaction Type codes to be allowed

### What did you see?

line:4 record:Addenda *ach.FieldError TransactionTypeCode mis is an invalid Addenda10 Transaction Type Code
  line:14 record:Batches *ach.BatchError batch #20 (IAT) FieldError Addenda10 <nil> is a mandatory field and has a default value

### How can we reproduce the problem?

Process an Addenda 10 with a lower case `MIS` as the transaction type

**Comment by adamdecaf** [comment]
Thanks for reporting this bug. My copy of the Nacha rules states they should be in uppercase, but the real world is always different. We're just going to convert those to uppercase for the validation. That way you can read the exact bytes that was sent. 

I noticed that a few codes are missing which are valid in the 2021 rules, so I've added those as well. 

Can you take a look at https://github.com/moov-io/ach/pull/1128 ?

**Comment by kmyers94** [comment]
Interesting, our copy makes no mention of case sensitivity at all. 🤷 I was going to put a PR up this morning but moov is on the ball! Thanks a bunch!

**Comment by adamdecaf** [comment]
This has been released https://github.com/moov-io/ach/releases/tag/v1.22.2
