### ISSUE TITLE
Library incompatible with go v1.16.15

### ISSUE THREAD

**Issue by kmyers94** [wadearnold/ach#1129]
### ACH Version

1.21.0 (last working version in process of moving from 1.18.5 -> 1.22.2)

### What were you trying to do?

While attempting to upgrade to the newest version of the library, ATOW 1.22.2, testify changes version v1.8.0 -> v1.8.1 @ v1.22.X (https://github.com/moov-io/ach/releases/tag/v1.22.0) This is a backward incompatible change for go version 1.16.X

The root cause seems to be coming from the `x` package specifically a switch to `unsafe.Slice`

### What did you expect to see?

No error upgrading moov from version 1.18.5 -> 1.22.2

### What did you see?

```
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall.go:83:16: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_darwin.go:95:8: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
```

### How can we reproduce the problem?

Using go version 1.16.15 attempt to utilize moov-io/ach@v1.22.2

**Comment by adamdecaf** [comment]
I don't think we have this stated, but we tend to follow Go's release policy where only the latest two major releases are supported. Go 1.19 is currently out so we would only support Go 1.19.x and Go 1.18.x 

go1.16.15 (released 2022-03-03) is fairly out of date, so I'm not sure we can support it. 

https://go.dev/doc/devel/release#policy

Edit: golang.org/x/sys is a package maintained by the Go team so releases of that library will follow their release policy. We don't have control over that package and can't risk importing an insecure version of golang.org/x/sys

**Comment by adamdecaf** [comment]
Would a v1.21.3 release with the Addenda10 change you reported work for you? I could cherry-pick that fix and release it for you.

**Comment by kmyers94** [comment]
>Would a v1.21.3 release with the Addenda10 change you reported work for you? I could cherry-pick that fix and release it for you.

that could work.

That makes sense, I figured it was a long shot and we would have to bite the bullet and upgrade. Been kicking the can down the road because of other things. The readme does not guarantee compatibility but it might be good to remove/modify this line https://github.com/moov-io/ach/blob/v1.22.2/README.md?plain=1#L234 I think the minimum version for compatibility is now 1.17

**Comment by kmyers94** [comment]
On second thought don't trouble yourself with releasing 1.21.3 I am going to upgrade to the newest go version and be done with it 😄 Thanks!

**Comment by adamdecaf** [comment]
Okay, sounds good!
