### ISSUE TITLE
Feature Request: Preserve spacing when parsing ACH file

### ISSUE THREAD

**Issue by AndrewPecha** [wadearnold/ach#1159]
### ACH Version

1.27.0

### What were you trying to do?

I was attempting to parse an entire ACH file to JSON using the /create POST endpoint and preserve the leading and trailing spaces for  `CompanyIdentification` in `batchHeader.go`.

Instead, a value of " 123456789" or "123456789 " evaluates to "123456789" with the leading or trailing space removed

### What did you expect to see?

A way to enable a parsing option to preserve spacing of certain elements that normally trim leading/trailing spaces when they are parsed

I know my use case of only caring about `CompanyIdentification` is pretty small, so would it make sense to create an option for the parsers to preserve these leading/trailing spaces where `strings.TrimSpace()` is normally called?

**Comment by adamdecaf** [comment]
Yea, we could add a `PreserveSpaces bool` option. Could you open a pull request? It's not quite a ValidateOpt, but I don't want another struct (e.g. `ReaderOpts`).

**Comment by AndrewPecha** [comment]
Fair enough, that makes sense to me too. I can get a PR submitted in the next couple days.

Thank you!

**Comment by adamdecaf** [comment]
Fixed in https://github.com/moov-io/ach/pull/1162
