### ISSUE TITLE
During NACHA validation, did not catch prenote issue

### ISSUE THREAD

**Issue by bdeyerlyfsb** [wadearnold/ach#1168]
### ACH Version

1.28.0

### What were you trying to do?

Sometimes there could be specific transactions that are for prenote.

Prenote means, they send a zero dollar amount transaction to verify account and routing numbers.

I would suggest ACH verification checks to make sure the transaction code matches for any prenotes.

Pre-Note: Checking Deposit (Credit)
23

Pre-Note: Share Deposit (Credit)
33

Pre-Note: GL Deposit (Credit)
43

Pre-Note: Loan Deposit (Credit)
53

Pre-Note: Checking Withdrawal (Debit)
28

Pre-Note: Share Withdrawal (Debit)
38

Pre-Note: GL Withdrawal (Credit)
48

### What did you expect to see?

NACHA validation error if transaction amount is 0 - and there is not a transaction code that identifies a prenote.

### What did you see?

file contains monetary t/c with zero amount

### How can we reproduce the problem?

Create a 0 dollar transaction with any transaction code that is not identified as a prenote transaction. Such as 22, 32 or 27.

**Comment by adamdecaf** [comment]
Do you have a test case that shows the bug?

**Comment by bdeyerlyfsb** [comment]
101 231380104 1210428821907181055A094101Federal Reserve Bank   My Bank Name                   
5200Name on Account                     121042882 PPDREG.SALARY      190719   1121042880000001
627231380104123456789        0200000000               Debit Account           0121042880000001
632231380104987654321        0000000000               Credit Account 1        0121042880000002
622231380104837098765        0100000000               Credit Account 2        0121042880000003
82000000030069414030000200000000000100000000121042882                          121042880000001
9000001000001000000030069414030000200000000000100000000                                       
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

**Comment by bdeyerlyfsb** [comment]
> Do you have a test case that shows the bug?

All you would need to do is use any example and place a 0 amount for any tran code that is not a prenote.

Scneario:

1. If transaction is 0 amount - check to make sure it is a prenote transaction.
2. IF NOT prenote transaction - throw an error.

**Comment by adamdecaf** [comment]
It's a bit more complicated than that to properly handle all SEC codes, but I'll take a look.

**Comment by bdeyerlyfsb** [comment]
> It's a bit more complicated than that to properly handle all SEC codes, but I'll take a look.

Maybe not handle all transaction codes. What you could do is check for zero amounts and throw a generic error? ACH entries should not be zero amounts. Only during prenotes.

**Comment by adamdecaf** [comment]
ACK (and ATX) entries must have zero amounts. NOC's will have a zero'd Amount value as well.

**Comment by adamdecaf** [comment]
A fix has been included in the latest release. @bdeyerlyfsb can you try it out and let us know? 

Release notes: https://github.com/moov-io/ach/releases/tag/v1.28.1

**Comment by bdeyerlyfsb** [comment]
> A fix has been included in the latest release. @bdeyerlyfsb can you try it out and let us know?
> 
> Release notes: https://github.com/moov-io/ach/releases/tag/v1.28.1

It looks like its working! Thanks a ton for adding this feature.
