### ISSUE TITLE
Addenda10 transaction type code does not appear to be widely validated by others/the Fed

### ISSUE THREAD

**Issue by zbruhnke** [wadearnold/ach#1195]
### ACH Version

v1.29.3

### What were you trying to do?

We recently received a file with a transaction incoming from a major bank (Top 5 in the US) that came with an addenda10 and it appears that neither they nor the Fed are actually validating the transaction type code for Addenda10 

In this case it literally used the code `IAT` which is not one of the possible options.

It would be great to optionally have the ability to bypass the validation of these fields like we do for others

### What did you expect to see?

a bypass validation option

### What did you see?

no way to bypass validation for this particular item

### How can we reproduce the problem?

create an ACH file with an Addenda10 and in the transaction type code use `IAT`

**Comment by adamdecaf** [comment]
Page OG189 of the 2022 rules I've got handy:
> There is no requirement to add Secondary SEC Codes for PPD, CCD, CTX, and other SEC codes not included in the list above. 

The inbound list includes: ARC, BOC, MTE, POP, POS, RCK, SHR, TEL, WEB. 

It looks like we should accept IAT as a value there. Does your transaction match the conditions where IAT is valid?

**Comment by zbruhnke** [comment]
yep it does!

**Comment by zbruhnke** [comment]
@adamdecaf can you build a docker image with this and I can test it against the file in question?

**Comment by adamdecaf** [comment]
Can you try `moov/ach:dev-d3d639a6`?

**Comment by adamdecaf** [comment]
I've pushed `moov/ach:dev-0fce919`. Can you try @zbruhnke and @germainc
