### ISSUE TITLE
Offset trace number removes leading zero

### ISSUE THREAD

**Issue by germainc** [wadearnold/ach#1197]
### ACH Version

dev-d3d639a6

### What were you trying to do?

Using the offset field in the request, if the trace numbers start with zero, the offset trace number strips off the leading zero.

### What did you expect to see?

"traceNumber": "088888880123459"

### What did you see?

"traceNumber": "88888880123459"

### How can we reproduce the problem?

Create an ACH file with an offset where the trace number begins with zero. The resulting ACH file contents appears to add back the zero but it's missing from the JSON.

**Comment by adamdecaf** [comment]
Thanks for reporting this! I've opened up https://github.com/moov-io/ach/pull/1199 as a fix.
