### ISSUE TITLE
CTX Returns both require and forbid addenda 5 records. 

### ISSUE THREAD

**Issue by kmyers94** [wadearnold/ach#1208]
### ACH Version

1.22.2

### What were you trying to do?

When creating a return record for a CTX entry if an added 5 record is not present validation errors out with the error:

`batch #1 (CTX) AddendaCount 0 addendum found where 1 are Expected for this batch type`

However when adding the addenda validation also fails with the error:

`batch #1 (CTX) Addenda05 this batch type does not allow this addenda for category: Return`

This effectively means Moov cannot validate any return file generated with a CTX record present. 

### What did you expect to see?

No validation error when omitting addenda 5 in the return.

### What did you see?

see above

### How can we reproduce the problem?

Create an ach file with a return entry (append addenda 99) for SEC code CTX with and without addenda 5. Validate the file and see the error.

**Comment by adamdecaf** [comment]
Is this still an issue with v1.30.0 of moov-io/ach?

**Comment by sunnygill-stash** [comment]
I was able to reproduce this error in 1.30.0.  When we run the test below, we get 

> batch #1 (CTX) AddendaCount 0 addendum found where 1 are Expected for this batch type.  

If we add an addenda 05 record, we get 

> batch #1 (CTX) Addenda05 this batch type does not allow this addenda for category: Return.

  It seems like validation rules for non-return batches are being applied to returns. 

```

func Test_Moov_IO_Error(t *testing.T) {
	batchHeader := ach.NewBatchHeader()
	batchHeader.ServiceClassCode = 200
	batchHeader.CompanyDiscretionaryData = "1"
	batchHeader.CompanyName = "2"
	batchHeader.CompanyIdentification = "3"
	batchHeader.StandardEntryClassCode = "CTX"
	batchHeader.CompanyEntryDescription = "5"
	batchHeader.CompanyDescriptiveDate = "6"
	batchHeader.EffectiveEntryDate = "7"

	batchHeader.ODFIIdentification = "8"
	batch, batchErr := ach.NewBatch(batchHeader)
	require.NoError(t, batchErr)

	batch.SetValidation(&ach.ValidateOpts{CustomTraceNumbers: true})

	entryDetail := ach.NewEntryDetail()
	entryDetail.TransactionCode = 26
	entryDetail.RDFIIdentification = "87654321"
	entryDetail.CheckDigit = "2"
	entryDetail.DFIAccountNumber = "123456789"
	entryDetail.Amount = 123
	entryDetail.IdentificationNumber = "10"
	entryDetail.IndividualName = "0001Whatevs"

	entryDetail.DiscretionaryData = "DD"
	entryDetail.TraceNumber = "500"
	entryDetail.Category = "Return"

	batch.AddEntry(entryDetail)

	addenda99 := ach.NewAddenda99()
	addenda99.ReturnCode = "R05"
	addenda99.OriginalTrace = "500"
	addenda99.TraceNumber = "600"
	addenda99.OriginalDFI = "12345678"
	entryDetail.Addenda99 = addenda99
	entryDetail.AddendaRecordIndicator = 1

	require.NoError(t, batch.Create())

	assert.NoError(t, batch.Validate())
}

```

**Comment by adamdecaf** [comment]
Thanks for opening this issue @kmyers94! I've opened a PR that fixes your issues and improves the setters/getters. Can you take a look? https://github.com/moov-io/ach/pull/1216
