### ISSUE TITLE
-log.format=json actually does key-value logging, not JSON

### ISSUE THREAD

**Issue by sfcodes** [wadearnold/ach#1232]
### ACH Version

Since v1.14.0

### What were you trying to do?

Explicitly set logging to JSON or "plain" using command line argument ` -log.format`

### What did you expect to see?

For `./server -log.format=json` I expected JSON logging, and for `./server -log.format=plain` plain.

### What did you see?

```
❯ ./server -log.format=json
ts=2023-05-19T20:03:02Z msg="Starting ach server version v1.31.2" level=info
ts=2023-05-19T20:03:02Z msg="startup binding to :8080 for HTTP server" level=info
ts=2023-05-19T20:03:02Z msg="admin listening on [::]:9090" level=info
^Cts=2023-05-19T20:03:12Z msg=interrupt errored=true level=info
ts=2023-05-19T20:03:12Z msg="problem starting admin http: http: Server closed" errored=true level=info
```

While setting to `plain` results in JSON...
```
❯ ./server -log.format=plain
{"level":"info","msg":"Starting ach server version v1.31.2","ts":"2023-05-19T20:03:16Z"}
{"level":"info","msg":"startup binding to :8080 for HTTP server","ts":"2023-05-19T20:03:16Z"}
{"level":"info","msg":"admin listening on [::]:9090","ts":"2023-05-19T20:03:16Z"}
^C{"errored":true,"level":"info","msg":"interrupt","ts":"2023-05-19T20:03:28Z"}
{"errored":true,"level":"info","msg":"problem starting admin http: http: Server closed","ts":"2023-05-19T20:03:28Z"}
```

_Note that it's reversed. Setting to json results in plan, and vice versa._

### How can we reproduce the problem?

Run `./server -log.format=json`, and you'll see the logs _not_ JSON formatted.

**Comment by sfcodes** [comment]
This appears to be a simple reverse-logic bug in https://github.com/moov-io/ach/blob/5d203a9488c16d01df8542e0a290740f433e22af/cmd/server/main.go#L58

I think it should be...
```
if *flagLogFormat == "json" {
  kitlogger = kitlog.NewJSONLogger(kitlog.NewSyncWriter(os.Stdout))    // <-- swapped 
} else {
  kitlogger = kitlog.NewLogfmtLogger(kitlog.NewSyncWriter(os.Stdout))  // <-- swapped 
}
```

**Comment by adamdecaf** [comment]
Thanks for reporting this bug. We'll get a bugfix release out.
