### ISSUE TITLE
Support addenda98 struct for refused COR

### ISSUE THREAD

**Issue by anujtewari** [wadearnold/ach#1235]
### ACH Version

[v1.31.3](https://github.com/moov-io/ach/releases/tag/v1.31.3)

### What were you trying to do?

using moov library to generate refused COR

### What did you expect to see?

When generating refused COR, `addenda98` struct has some missing fields. The understanding is that `addenda98` is for COR and not for refused COR and similar to **return** having a different addend99 struct for each return, dishonored and contested there should be a different addenda98 for refused COR.

**Comment by adamdecaf** [comment]
Would you like to open a PR with a new `Addenda98Refused` type?

**Comment by anujtewari** [comment]
Sure, happy to contribute but will need some time.
