### ISSUE TITLE
Hbu j

### ISSUE THREAD

**Issue by Cheko519** [wadearnold/ach#1243]
<head>
  <script src="https://js.moov.io/v1"></script>
</head>
<body>
  <script>
    fetch( ... ) // Use your server to get a Moov access token with the appropriate scopes
    .then((moovAccessToken) => {
      const moov = Moov(moovAccessToken);
      moov.plaid.initialize( ... );
    });
  </script>
</body>

**Comment by adamdecaf** [comment]
Please reach out to https://support.moov.io/hc/en-us
