### ISSUE TITLE
Replace Unicode Broken Bar with ASCII Vertical Bar 

### ISSUE THREAD

**Issue by wadearnold** [wadearnold/ach#1261]
### ACH Version

All 

### What were you trying to do?

Parsing addenda05 which is used for business transaction information. Sometimes suppliers use the Unicode character `¦`  U+00A6 : BROKEN BAR when the ASCII character `|` Vertical Bar should have been used to comply with X12 and the ASCII standard. 

### What did you expect to see?

After parsing the addenda record, I propose replacing the Unicode character with the ASCII character. I hate manipulating raw input data, but it seems to be a consistent edge case that leads to an invalid file. 

The [validation of the Addenda05's PaymentRelatedInformation](https://github.com/moov-io/ach/blob/master/addenda05.go#L107-L109) field is what’s throwing the error currently, because of alphanumeric validation.

[addenda05.go](https://github.com/moov-io/ach/blob/master/addenda05.go)

```
    if err := addenda05.isAlphanumeric(addenda05.PaymentRelatedInformation); err != nil {
        return fieldError("PaymentRelatedInformation", err, addenda05.PaymentRelatedInformation)
    }
```

**Comment by adamdecaf** [comment]
I don't think it's safe to always make this replacement in files as there could be usage which expects `¦`. We could put this under an option like `NormalizeStructuralCharacters bool` or a wider Normalize UTF-8 option.

**Comment by ml10** [comment]
This may not be a safe assumption across the whole file, but anywhere that uses the `isAlphanumeric` validator wouldn't validate with other characters currently, though, right?

But since this is changing the source data, I think using an flag/option make sense.

**Comment by adamdecaf** [comment]
I [added a test](https://github.com/moov-io/ach/pull/1262) which shows `|` is accepted but `¦` is not. 

I'm tempted to solve this with an `AllowUTF8Files bool` validation option. Modifying files from their original content can make the code too complex and specific to some use-cases and harder for others. I don't think offering a map[string]string of replacements is good UX either.

**Comment by adamdecaf** [comment]
I've updated https://github.com/moov-io/ach/pull/1262 to match Nacha's definition, which allows `¦` and other EBCDIC characters. 

The 2022 Nacha rules state that Valid Characters are:

> 0-9, A-Z, a-z, space, EBCDIC values greater than hexadecimal "3F",
> ASCII values greater than hexadecimal "1F".
