### ISSUE TITLE
Bug in ach.WriteCorrectionData() with C03 and 17 character account number

### ISSUE THREAD

**Issue by viggykuppu** [wadearnold/ach#1278]
https://github.com/moov-io/ach/blob/8a108199386d615d38e8f3b61ad18b92a90e9aaf/addenda98.go#L331

`ach.WriteCorrectionData("C03",  correctedData)` panics when using `correctedData: &{AccountNumber:cDgvNMS41YdAlj0XD RoutingNumber:021000021 Name: TransactionCode:0 Identification:}`

Error is:` panic: strings: negative Repeat count`

**Comment by adamdecaf** [comment]
Thank you for reporting this @viggykuppu!
