### ISSUE TITLE
Error parsing test file 

### ISSUE THREAD

**Issue by ChillOrb** [wadearnold/ach#1280]
### ACH Version 

https://oss.moov.io/ach/ v1.31.3

### What were you trying to do?

1. Was going over documentation here: https://oss.moov.io/ach/ and trying to use one of the test file to try parser

### What did you expect to see?

Successful parse

### What did you see?

3. While trying the first [test file](https://github.com/moov-io/ach/blob/master/test/testdata/20110729A.ach) , got error `unable to parse ach file: line:1 record:FileHeader ach.RecordWrongLengthErr must be 94 characters and found 93
  line:1 record:FileHeader *ach.FieldError FileCreationDate  is a mandatory field and has a default value, did you use the constructor?
  line:2 record:BatchHeader *ach.FieldError StandardEntryClassCode PDT is an invalid Standard Entry Class Code`

### How can we reproduce the problem?

Go to [test file](https://github.com/moov-io/ach/blob/master/test/testdata/20110729A.ach)
View file as raw, copy text , paste in https://oss.moov.io/ach/ 
Also tried uploading the file , same error

Most likely just file format error..

**Comment by adamdecaf** [comment]
That file is probably invalid. You can parse valid files such as 
https://github.com/moov-io/ach/blob/master/test/testdata/20110805A.ach

**Comment by adamdecaf** [comment]
Thanks for letting us know that file could be named better.
