### ISSUE TITLE
IAT Returns sample file required. 

### ISSUE THREAD

**Issue by ganesh-solid** [wadearnold/ach#1376]
### ACH Version

v1.9.2

### What were you trying to do?

1. I was trying to return an IAT transactions, currently it does not add the IAT entries to "ReturnEntries" field. Is there any example of IAT return? or is IAT returns are handled seperately?

### What did you expect to see?

I expected to see IAT being populated at "ReturnEnties" field.

**Comment by adamdecaf** [comment]
The `IATBatch` type does not currently implement the `ach.Batcher` interface, so we can't include them on the root level helper.

```
./iatBatch.go:49:17: cannot use (&IATBatch{}) (value of type *IATBatch) as Batcher value in variable declaration: *IATBatch does not implement Batcher (missing method AddADVEntry)
```
```
./iatBatch.go:49:17: cannot use (&IATBatch{}) (value of type *IATBatch) as Batcher value in variable declaration: *IATBatch does not implement Batcher (wrong type for method AddEntry)
		have AddEntry(*IATEntryDetail)
		want AddEntry(*EntryDetail)
```

**Comment by ganesh-solid** [comment]
@adamdecaf Do you have any sample file for IAT returns? How do we file returns for IAT ach transactions then?

**Comment by adamdecaf** [comment]
Any examples we could share would be in this repository. Moov isn't using the IAT part of this library currently, but we have many users of the library who are sending IAT files. 

An [`IATEntryDetail` has a field for Addenda99](https://pkg.go.dev/github.com/moov-io/ach#IATEntryDetail.Addenda99) which would be where you'd specify the Return record / information.

**Comment by adamdecaf** [comment]
@ganesh-solid has your question been answered?
