### ISSUE TITLE
ACH Incoming file does not have a Foreign Exchange Reference Indicator, can we allow for the validation of this field to be skipped

### ISSUE THREAD

**Issue by nitu-luna** [wadearnold/ach#1462]
### ACH Version

1.14.0

### What were you trying to do?

Parse and validate an incoming ACH file

### What did you expect to see?

Expecting the ach file to successfully parsed and validated. 

### What did you see?

ACH parse error: line:2628 record:BatchHeader *ach.FieldError ForeignExchangeReferenceIndicator 0 is a required field\n  

ForeignExchangeReferenceIndicator in the incoming file for the IAT entry was set to blank. According to the spec, blank is not a valid value. However, since this is a required field, and not mandatory, the ach operator sends the entry and does not reject it. 

As ODFI, we need to be able to process this entry, but we are unable to do so as the moov validation fails. Is it possible to have a skip validation for "ForeignExchangeReferenceIndicator" to indicate skipping the validation of this field.

### How can we reproduce the problem?

Set the "ForeignExchangeReferenceIndicator" as blank for an IAT entry

**Comment by adamdecaf** [comment]
We talked in slack and allowing 0 iff FF makes the most sense as a compromise.

**Comment by adamdecaf** [comment]
Released in https://github.com/moov-io/ach/releases/tag/v1.41.1
