### ISSUE TITLE
Cannot create a return file for SEC code CTX

### ISSUE THREAD

**Issue by chomreunsop** [wadearnold/ach#1501]
### ACH Version

v1.42.0

### What were you trying to do?

I'm trying to create a return file for SEC code CTX by using addenda99. 

Json format:
`{
	"fileHeader": {
		"immediateOrigin": "084106768",
		"immediateOriginName": "EVOLVE BANK & TRUST",
		"immediateDestination": "081000045",
		"immediateDestinationName": "FEDERAL RESERVE BANK",
		"fileCreationDate": "240602",
		"fileCreationTime": "1614"
	},
	"fileADVControl": {
		"batchCount": 0,
		"entryAddendaCount": 0,
		"entryHash": 0,
		"id": "",
		"totalCredit": 0,
		"totalDebit": 0
	},
	"batches": [
		{
			"batchHeader": {
				"companyName": "ben10",
				"companyIdentification": "1113290945",
				"standardEntryClassCode": "CTX",
				"companyEntryDescription": "RETURN",
				"ODFIIdentification": "08410676",
				"effectiveEntryDate": "230603",
				"serviceClassCode": 220
			},
			"entryDetails": [
				{
					"AddendaRecordIndicator": 1,
					"id": "16857152524021c",
					"amount": 1000,
					"traceNumber": "025405790000009",
					"RDFIIdentification": "06200001",
					"transactionCode": 22,
					"checkDigit": "9",
					"DFIAccountNumber": "000000012",
					"individualName": "Test",
					"identificationNumber": "ALEXA SMART",
					"category": "Return",
					"addenda99": {
						"typeCode": "99",
						"returnCode": "R06",
						"addendaInformation": "No Account/Unable to Locate Account",
						"originalDFI": "06200001",
						"originalTrace": "084106760000001",
						"traceNumber": "084106760000005"
					}
				}
			]
		}
	],
	"fileControl": {
		"batchCount": 1,
		"blockCount": 1,
		"entryAddendaCount": 2,
		"entryHash": 8410676,
		"id": "",
		"totalCredit": 6,
		"totalDebit": 0
	}
}`

**Error**: `"error": "batch #1 (CTX) AddendaCount 1 addendum found where 0 are expected for this batch type"`

### What did you expect to see?

File should be able to create.

### What did you see?

error message say: `batch #1 (CTX) AddendaCount 1 addendum found where 0 are expected for this batch type`.

### How can we reproduce the problem?

Let's use the json data above

**Comment by chomreunsop** [comment]
Correct me if I'm wrong that CTX has other ways to generate a return file without addena99

**Comment by adamdecaf** [comment]
What would that other way be?

**Comment by adamdecaf** [comment]
I see what's wrong. It's due to CTX entries not having exactly the same fields as other EntryDetail records.
