### ISSUE TITLE
How can I parse a FedACH Acknowledgement file starting with "****** ACKNOWLEDGEMENT OF ACH FILE DEPOSITS ******" using Moov's ACH library?

### ISSUE THREAD

**Issue by mohdjishin** [wadearnold/ach#1504]
I'm working with FedACH Acknowledgement files that start with the header "****** ACKNOWLEDGEMENT OF ACH FILE DEPOSITS ******". I would like to parse these files to extract structured information, but I’m unsure if Moov’s ACH library supports parsing this specific format out of the box.

**Comment by adamdecaf** [comment]
Do you have a spec for a link where I can view more about that report? It sounds like a Fed report, not part of the Nacha ACH standard. 

Edit: all I can find is this link [achfahk691000134ain20200512085211959.ack.txt](https://github.com/user-attachments/files/17683503/achfahk691000134ain20200512085211959.ack.txt)

Tried to get some [code generated from the example](https://chatgpt.com/share/672e6e01-de48-8004-baaa-5e2928f64b9a), which needs some help.

**Comment by mohdjishin** [comment]
The file appears to be similar. Is there a library available to handle this? @adamdecaf

**Comment by adamdecaf** [comment]
Do you have a specification? We can get a library written quickly.

**Comment by mohdjishin** [comment]
@adamdecaf  not really. having similar file.what you shared

**Comment by adamdecaf** [comment]
Can you share it? Email me at adam@moov.io and we can get a parser up and running.

**Comment by adamdecaf** [comment]
@mohdjishin We aren't parsing these reports, so how is this issue closed/completed?
