### ISSUE TITLE
Is there a way to delete an entry from the batch?

### ISSUE THREAD

**Issue by tamil-muthukumar** [wadearnold/ach#1509]
### ACH Version

1.40.3

### What were you trying to do?

I'm looking for a way to delete an entry that has been added to the batch. 

**For example:** When I'm adding an entry to the batch during the NACHA file creation process, there are some situations where a particular entry causes the batch validation to fail. In those cases I want to remove that entry from the batch and move forward with adding that batch to the file. Upon scanning the `batcher` APIs, I couldn't find an API to delete an entry from the batch. So I was wondering if there is any alternate way to do the same thing?

### What did you expect to see?

Ability to delete an entry from the batch

### What did you see?

No API provided in `batcher`

### How can we reproduce the problem?

By adding an entry to the batch and try removing it

**Comment by tamil-muthukumar** [comment]
Any inputs on this Q folks?

**Comment by adamdecaf** [comment]
There's nothing currently in the API, but we could add something pretty easily. Do you want to open a PR?

**Comment by kevinbarbour** [comment]
This is something I've also run into a use for in our use of the library so I gave it a shot in #1511

**Comment by adamdecaf** [comment]
Released in https://github.com/moov-io/ach/releases/tag/v1.43.0

**Comment by tamil-muthukumar** [comment]
Awesome! thankyou @kevinbarbour and @adamdecaf for the super quick turnaround on this 👍
