### ISSUE TITLE
Incorrectly truncating the characters in utf8 string

### ISSUE THREAD

**Issue by nitu-luna** [wadearnold/ach#1510]
### ACH Version

1.41.1

### What were you trying to do?

We created an ach file, and found the file to be corrupted. One of the ach entries had an identification number set to Testée Samples01

### What did you expect to see?

Expected to see the identification number set to Testée Samples0, and a valid ach file.

### What did you see?

On creating the ach file, identification number got truncated to Testée Samples instead of Testée Samples0, and the ach file was corrupted, as it had one less character.

On debugging it, the bug is caused by the following code:
// alphaField Alphanumeric and Alphabetic fields are left-justified and space filled.
func (c *converters) alphaField(s string, max uint) string {
	ln := uint(utf8.RuneCountInString(s))
	if ln > max {
		return s[:max]
	}

	m := int(max - ln)
	pad, exists := spaceZeros[m]
	if exists {
		return s + pad
	}
	// slow path
	return s + strings.Repeat(" ", int(max-ln))
}

s[:max] does not truncate correctly, it just gives the first n bytes and not first n characters.

### How can we reproduce the problem?

Create an ach file where the ach entry detail has the string Testée Samples01 as the identification number.

**Comment by adamdecaf** [comment]
Thanks, that's defiantly a bug we should fix.

**Comment by adamdecaf** [comment]
fix released in https://github.com/moov-io/ach/releases/tag/v1.42.2
