### ISSUE TITLE
file ID modifier is reset to value A after calling to flatten

### ISSUE THREAD

**Issue by chomreunsop** [wadearnold/ach#1513]
### ACH Version

moov/ach:v1.42.1

### What were you trying to do?

I was trying to generate an outgoing file by increment `fileIDModifier` in `fileHeader`. I parsed fileIDModifier: 'B' to create a file and then call to /flatten endpoint however, got the value `A` instead.

### What did you expect to see?

Value of `fileIDModifier` should be received whatever we sent.

### What did you see?

fileIDModifier is 'A'

### How can we reproduce the problem?

1. create a file along with fileHeader.fileIDModifier and set value to any alphabet
2. use the file id and send to `/flatten`
3. observe

**Comment by adamdecaf** [comment]
Do you need a value other than "A" in your use-case? This is a bug but "A" is often used regardless of what the modifier should be.

**Comment by Klasens** [comment]
I'm going to take a look at this issue. I haven't seen too many cases where the File Modifier isn't "A".  I worked with one bank that processed about 50 files a day (Not all went through the Fed, many were internal postings between their fintech partners), but if they sent multiple files to the Fed within a single day's processing window they would increment to the next Alpha character for each additional file.

**Comment by adamdecaf** [comment]
Sounds good. We can defiantly support characters beyond A. The bug is probably from flattening creating a new FileHeader and forgetting to copy the ID Modifier.

**Comment by adamdecaf** [comment]
Fixed in https://github.com/moov-io/ach/pull/1518 

Released in https://github.com/moov-io/ach/releases/tag/v1.44.1
