### ISSUE TITLE
Moov Create Account

### ISSUE THREAD

**Issue by vijaystudio45** [wadearnold/ach#990]
I am trying to create an account using  https://api.moov.io/accounts  but it does not letting me to create an account and gives 401 unauthorized error. Here is the reference example - https://docs.moov.io/moovjs/authentication/ https://docs.moov.io/moovjs/accounts/accounts/

Please help me with this by providing a working example

**Comment by adamdecaf** [comment]
Hi @vijaystudio45 can you reach out to `support@moov.io` for help with this issue?
