### ISSUE TITLE
proposal: use time.Parse() in ValidateSimpleDate

### ISSUE THREAD

**Issue by tscales** [wadearnold/ach#996]
[ValidateSimpleDate](https://github.com/moov-io/ach/blob/master/validators.go#L136-L151) seems to have a lot of logic that could be simplified by using the `time` package. This would also solve the TODO of validating during a leap year. 

here is a possible implementation:

```Go
// validateSimpleDate will return the incoming string only if it matches a valid YYMMDD
// date format. (Y=Year, M=Month, D=Day)
func (v *validator) validateSimpleDate(s string) string {
	//YYMMDD
	layout := "060102"

	_, err := time.Parse(layout, s)
	if err != nil {
		return ""
	}
	return s
}
```

**Comment by adamdecaf** [comment]
Yea.. That date validation code was written a while ago and I don't remember why we chose to have `isDay` and related functions.

**Comment by adamdecaf** [comment]
Do you have a failing test case for this? 2024-02-29 passes the current implementation. 

Edit: "230229" is a date which should not be valid.
